### ISSUE TITLE
TypeError: The plugin "antd" didn't export a Plugin instance

### ISSUE THREAD

**Issue by GENGSHUANGs** [ant-design/babel-plugin-antd#11]
```
/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164
      throw new TypeError(messages.get("pluginNotTransformer", name));
      ^

TypeError: The plugin "antd" didn't export a Plugin instance
    at PluginManager.validate (/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/ball/site-home/hipack/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transformFileSync (/Users/ball/site-home/hipack/node_modules/babel-core/lib/api/node.js:137:37)
    at compile (/Users/ball/site-home/hipack/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/Users/ball/site-home/hipack/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ball/site-home/hipack/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:357:32)
```

请问这是什么原因造成的呢？

这是我的依赖包
```javascript
"dependencies": {
    "assets-webpack-plugin": "^3.2.0",
    "autoprefixer": "^6.1.2",
    "babel": "^5.8.34",
    "babel-eslint": "^4.1.6",
    "babel-loader": "^5.4.0",
    "babel-plugin-antd": "^0.3.2",
    "babel-plugin-react-transform": "^1.1.1",
    "browser-sync": "^2.10.1",
    "colors": "^1.1.2",
    "commander": "^2.9.0",
    "css-loader": "^0.23.0",
    "csscomb": "^3.1.8",
    "del": "^2.2.0",
    "eslint": "^1.10.3",
    "eslint-config-airbnb": "^2.1.1",
    "eslint-loader": "^1.1.1",
    "eslint-plugin-react": "^3.11.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gaze": "^0.5.2",
    "git-repository": "^0.1.1",
    "glob": "^6.0.1",
    "html-webpack-plugin": "^2.9.0",
    "isomorphic-style-loader": "0.0.5",
    "jest-cli": "^0.8.2",
    "jscs": "^2.7.0",
    "json-loader": "^0.5.4",
    "lodash.merge": "^3.3.2",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "postcss": "^5.0.13",
    "postcss-import": "^7.1.3",
    "postcss-loader": "^0.8.0",
    "precss": "^1.3.0",
    "progress-stream": "^1.2.0",
    "raw-loader": "^0.5.1",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "replace": "^0.3.0",
    "request": "^2.69.0",
    "unzip": "^0.1.11",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.9",
    "webpack-hot-middleware": "^2.6.0",
    "webpack-middleware": "^1.4.0"
  }
```

**Comment by sorrycc** [comment]
babel 插件名用 `babel-plugin-antd`，不要用 `antd` 。
