### ISSUE TITLE
Support `import { Select as Select2 } from 'antd';`

### ISSUE THREAD

**Issue by jasonslyvia** [ant-design/babel-plugin-antd#15]
**Current behaviour**

![image](https://cloud.githubusercontent.com/assets/1336484/15173224/81db6a9c-178d-11e6-91a0-5c6e0b76044e.png)
![image](https://cloud.githubusercontent.com/assets/1336484/15173227/8431566c-178d-11e6-8148-c35dd40ce074.png)

**Expected behaviour**

It should work properly.

**Env**

babel-plugin-antd: 0.4.0
antd: 1.0.0

**Comment by zhanjiaxia** [comment]
+1

**Comment by EduardoAC** [comment]
Good morning, 

On the version 1.1 of babel-import-plugin I got this issue when I ran my Jest tests. 

Could you help me with this?
Error 
```
Test suite failed to run

    Cannot find module 'antd/lib/ant-layout/style/css' from 'Layout.jsx'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (src/components/layout/Layout.jsx:1:339)
      at Object.<anonymous> (src/components/layout/Layout.test.js:4:41)
```

my package.json
```
{
  "name": "@cep/cep-platform-frontend",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    ...
    "babel-plugin-import": "^1.1.0",
    "babel-preset-react-app": "^2.0.1",
    "css-loader": "0.26.0",
    "dotenv": "2.0.0",
    "enzyme": "^2.6.0",
    "eslint": "^3.12.1",
    ...
    "html-webpack-plugin": "2.24.0",
    "jest": "17.0.2",
    "json-loader": "0.5.4",
    "node-sass": "^4.0.0",
    ....
    "sass-loader": "^4.1.0",
    "strip-ansi": "3.0.1",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.14.0",
    ...
  },
  "dependencies": {
    "antd": "^2.7.1",
    ...
    "express": "^4.14.0",
    "json-schema-deref-sync": "^0.3.3",
    "lodash": "^4.17.4",
    "morgan": "^1.7.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^4.4.6",
    "react-router": "^3.0.0",
    "react-router-bootstrap": "^0.23.1",
    "react-router-redux": "^4.0.7",
    "redux": "^3.6.0",
    "redux-api": "^0.9.16",
    "redux-auth": "0.0.5-beta5",
    "redux-form": "^6.4.1",
    "redux-thunk": "^2.1.0",
    "tv4": "^1.2.7",
    "tv4-formats": "^2.2.1",
    "validator-js": "^0.2.1"
  },
  "scripts": {
    ...
    "start:production": "node server",
    ...
    "test": "node scripts/test.js --env=jsdom",
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>[/\\\\](build|docs|node_modules)[/\\\\]"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    }
  },
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "import",
        {
          "libraryName": "antd",
          "style": "css"
        }
      ]
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

My layout.jsx
```
import React, { PropTypes } from 'react';
import { Layout as AntLayout } from 'antd';

import LeftMenu from '../left-menu/LeftMenuContainer';
import Header from '../header/HeaderContainer';
import Footer from '../footer/FooterContainer';

const { Content, Sider } = AntLayout;

const navigationLinks = [
  { to: '/', title: 'Home' },
];
const footerLinks = [
  { to: '/help', title: 'Help' },
];
const LayoutAntd = ({ children }) => (
  <AntLayout>
    <Header />
    <AntLayout>
      <Sider width="248" className="left-menu-container">
        <LeftMenu navigationLinks={navigationLinks} />
      </Sider>
      <Content>
        { children }
      </Content>
    </AntLayout>
    <Footer footerLinks={footerLinks} />
  </AntLayout>
);

LayoutAntd.propTypes = {
  children: PropTypes.node.isRequired,
};

export default LayoutAntd;
```

My layout.test.jsx
```
import React from 'react';
import { shallow } from 'enzyme';

import Layout from './Layout';

describe('<Layout>', () => {
  const wrapper = shallow(
    <Layout>{' '}</Layout>,
  );

  it('contains header', () => {
    expect(wrapper.find('Connect(Header)')).toHaveLength(1);
  });
...
});
```

**Comment by bwlt** [comment]
Same here.
btw in other modules when I'm importing like:
```
import {
  Layout as AntLayout,
  Breadcrumb,
  Row,
  Col,
} from 'antd'
```
It works

![screen shot 2017-05-26 at 16 05 35](https://cloud.githubusercontent.com/assets/4998750/26497861/497bdc4c-422d-11e7-80dc-260b24d1269a.png)
![screen shot 2017-05-26 at 16 05 54](https://cloud.githubusercontent.com/assets/4998750/26497862/49c2fc8a-422d-11e7-8cc8-218b18b5ba57.png)
