### ISSUE TITLE
css options error

### ISSUE THREAD

**Issue by mydearxym** [ant-design/babel-plugin-antd#47]
```js
"babel": {
    "presets": [
      "es2015-webpack",
      "react",
      "stage-0"
    ],
    "plugins": ["antd", { "style": "css" } ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      }
    }
  },

```

```js
Localhost: http://localhost:3000
      LAN: http://192.168.31.107:3000
-----------------------------------
Press CTRL-C to stop

webpack built ffe827e86599be33d88d in 1361ms

ERROR in ./app/app.js
Module build failed: Error: Plugin 1 specified in "/Users/xieyiming/code/coder_club/front_end/package.json" provided an invalid property of "style"
    at Plugin.init (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/plugin.js:138:13)
    at Function.normalisePlugin (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/options/option-manager.js:147:12)
    at /Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-loader/index.js:88:12)
 @ multi main
Child html-webpack-plugin for "index.html":
```

**Comment by afc163** [comment]
plugins 的格式写错了。

**Comment by mydearxym** [comment]
thanks @afc163   

i fix the plugins format, but other error came out: 
```js
webpack built 466c2fff89332aad328d in 10912ms

ERROR in ./app/containers/HomePage/index.js
Module build failed: TypeError: /Users/xieyiming/code/coder_club/front_end/app/containers/HomePage/index.js: Cannot read property '0' of null
    at Buffer._append (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/buffer.js:96:25)
    at Buffer.append (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/buffer.js:68:10)
    at Generator._append (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:255:52)
    at Generator.word (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:157:10)
    at Generator.Identifier (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/generators/types.js:43:8)
    at /Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:372:23
    at Buffer.withSource (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/buffer.js:180:5)
    at Generator.withSource (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:238:15)
    at Generator.print (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:371:10)
    at Generator.ImportSpecifier (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/generators/modules.js:22:8)
    at /Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:372:23
    at Buffer.withSource (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/buffer.js:180:5)
    at Generator.withSource (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:238:15)
    at Generator.print (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:371:10)
    at Generator.printJoin (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:443:12)
    at Generator.printList (/Users/xieyiming/code/coder_club/front_end/node_modules/babel-generator/lib/printer.js:507:17)
 @ ./app/routes.js 31:129-165

ERROR in chunk main [entry]
1.chunk.js
Cannot read property 'id' of null
```

maybe  the same with issue #43

**Comment by sorrycc** [comment]
这个报错，看起来不是这个插件的问题。
