### ISSUE TITLE
Module build failed: Error: Plugin 0 specified in

### ISSUE THREAD

**Issue by motorguo** [ant-design/babel-plugin-antd#60]
**webpack编译报：**

```
"babel-plugin-antd": "^0.5.1",
"antd-mobile": "^0.7.8",

npm -v
3.8.9

node -v
v6.2.0
```

```
ERROR in ./src/entries/index.js
Module build failed: Error: Plugin 0 specified in "D:\\..省略路徑..\\.babelrc.env.develo
pment" provided an invalid property of "libraryName"
    at Plugin.init (D:\..省略路徑..\node_modules\babel-core\lib\transformation\plugin.js
:131:13)
    at Function.normalisePlugin (D:\..省略路徑..\node_modules\babel-core\lib\transformat
ion\file\options\option-manager.js:144:12)
    at D:\..省略路徑..\node_modules\babel-core\lib\transformation\file\options\option-ma
nager.js:176:30
    at Array.map (native)
    at Function.normalisePlugins (D:\..省略路徑..\node_modules\babel-core\lib\transforma
tion\file\options\option-manager.js:150:20)
    at OptionManager.mergeOptions (D:\..省略路徑..\node_modules\babel-core\lib\transform
ation\file\options\option-manager.js:224:36)
    at OptionManager.init (D:\..省略路徑..\node_modules\babel-core\lib\transformation\fi
le\options\option-manager.js:338:12)
    at File.initOptions (D:\..省略路徑..\node_modules\babel-core\lib\transformation\file
\index.js:216:65)
    at new File (D:\..省略路徑..\node_modules\babel-core\lib\transformation\file\index.j
s:137:24)
    at Pipeline.transform (D:\..省略路徑..\node_modules\babel-core\lib\transformation\pi
peline.js:46:16)
    at transpile (D:\..省略路徑..\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (D:\..省略路徑..\node_modules\babel-loader\index.js:131:12)

 @ multi app
```
`//.babelrc`
```
{
    "presets": ["react", "es2015", "stage-0"],
    "env": {
        "development": {
            "plugins": [
                [
                  { libraryName: "antd", libraryDirectory: "lib", style: true,},
                  { libraryName: "antd-mobile",libraryDirectory: "component",},
                ],
                ["react-transform", {
                    "transforms": [{
                        "transform": "react-transform-hmr",
                        "imports": ["react"],
                        "locals": ["module"]
                    }, {
                        "transform": "react-transform-catch-errors",
                        "imports": ["react", "redbox-react"]
                    }]
                }],
            ]
        }
    }
}
```
`//webpack`
```
modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],
extensions: ['', '.web.js', '.js', '.jsx', 'json', '.css'],
```

**Comment by sorrycc** [comment]
babel-plugin-antd 版本是 0.5.x 吗?

**Comment by motorguo** [comment]
@sorrycc 是的

**Comment by sorrycc** [comment]
配置错了，改成这样：

```javascript
['antd', [
  { libraryName: "antd", libraryDirectory: "lib", style: true,},
  { libraryName: "antd-mobile",libraryDirectory: "component",},
]],
```

**Comment by motorguo** [comment]
```
ERROR in ./~/normalize.css/normalize.css
Module parse failed: D:\...\node_modules\normalize.css\normalize.css Unexpected
 token (9:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (9:5)
    at Parser.pp$4.raise (D:\...\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\...\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (D:\...\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (D:\...\node_modules\acorn\dist\aco
rn.js:966:10)
    at Parser.pp$1.parseStatement (D:\...\node_modules\acorn\dist\acorn.js:730:
24)
    at Parser.pp$1.parseTopLevel (D:\...\node_modules\acorn\dist\acorn.js:638:2
5)
    at Parser.parse (D:\...\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (D:\...\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\...\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (D:\...\node_modules\webpack\lib\NormalMod
ule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\...\node_modules\webpack-core\lib\No
rmalModuleMixin.js:310:10)
    at nextLoader (D:\...\node_modules\webpack-core\lib\NormalModuleMixin.js:27
5:25)
    at D:\...\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\...\node_modules\enhanced-resolve\lib\CachedInputFi
leSystem.js:38:16)
    at D:\...\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/antd-mobile/lib/style/index.js 3:0-38
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 10.3 kB [rendered]
        [0] ./~/css-loader!./~/less-loader!./~/antd-mobile/lib/icon/style/index.less 8.84 kB {0} [bui
lt]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 4.78 kB [rendered]
        [0] ./~/css-loader!./~/less-loader!./~/antd-mobile/lib/style/index.less 3.27 kB {0} [built]
        [4] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 4.41 kB [rendered]
        [0] ./~/css-loader!./~/less-loader!./~/antd-mobile/lib/button/style/index.less 2.9 kB {0} [bu
ilt]
        [4] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
```

//webpack
> loaders 也有加了
```
{test: /\.css$/, loader: ExtractTextPlugin.extract('style', '!css?modules&localIdentName=[local]-[hash:base64:5]&importLoaders=!postcss')},
            {test: /\.scss$/, loader: ExtractTextPlugin.extract('style', '!css!sass?sourceMap=true')},
            {test: /\.less$/, loader: ExtractTextPlugin.extract('style','!css!less')},
```
@sorrycc

**Comment by sorrycc** [comment]
这个不是 babel-plugin-antd 的问题了。

**Comment by motorguo** [comment]
@sorrycc 那估计是 `loaders` 配得有问题了！谢谢你了！
