### ISSUE TITLE
TypeError: arguments[i].apply is not a function

### ISSUE THREAD

**Issue by silverPanda** [ant-design/babel-plugin-antd#63]
webpack:1.13.2

confing 里面的
`{
  "plugins": [["antd", [{ "libraryName": "antd", "style": true }]]]
}`

结果报一下这个错误：
`[11:38:38] TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/LEO/Workspace/Eyes/node_modules/.0.1.10@tapable/lib/Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (/Users/LEO/Workspace/Eyes/node_modules/.1.13.2@webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/Users/LEO/Workspace/Eyes/node_modules/.1.13.2@webpack/lib/webpack.js:22:48)
    at Stream.<anonymous> (/Users/LEO/Workspace/Eyes/node_modules/.3.2.0@webpack-stream/index.js:131:20)
    at _end (/Users/LEO/Workspace/Eyes/node_modules/.2.3.8@through/index.js:65:9)
    at Stream.stream.end (/Users/LEO/Workspace/Eyes/node_modules/.2.3.8@through/index.js:74:5)
    at module.exports (/Users/LEO/Workspace/Eyes/node_modules/.3.2.0@webpack-stream/index.js:200:12)
    at Gulp.<anonymous> (/Users/LEO/Workspace/Eyes/gulpfile.js:90:15)
    at module.exports (/Users/LEO/Workspace/Eyes/node_modules/.0.3.7@orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/LEO/Workspace/Eyes/node_modules/.0.3.7@orchestrator/index.js:273:3)`

**Comment by sorrycc** [comment]
配错了，要 `['antd', opts]`，看 README，https://github.com/ant-design/babel-plugin-antd#usage

**Comment by silverPanda** [comment]
@sorrycc 打错了  已经更正，感觉是不是我的webpack的版本太高了，我看官网的plugin的说明是这样的：
```javascript
// MyPlugin.js

function MyPlugin(options) {
  // Configure your plugin with options...
}

MyPlugin.prototype.apply = function(compiler) {
  compiler.plugin("compile", function(params) {
    console.log("The compiler is starting to compile...");
  });

  compiler.plugin("compilation", function(compilation) {
    console.log("The compiler is starting a new compilation...");

    compilation.plugin("optimize", function() {
      console.log("The compilation is starting to optimize files...");
    });
  });

  compiler.plugin("emit", function(compilation, callback) {
    console.log("The compilation is going to emit files...");
    callback();
  });
};

module.exports = MyPlugin;
```
```javascript
plugins: [
        new MyPlugin({options: 'nada'})
]
```

**Comment by silverPanda** [comment]
我的错。。。。。写到webpack的plugins里面了。。。。。
